
## Data Mining, BI-VZD
## Home Assignment 1 - Part 1 - Scrapping
### Bc. Jiří Zelenka
### UK-FSV-IES

####################################################################################

## Content:

<a id='1_Introductory'></a>
[1_Introductory](#1_Introductory)

 * <a id='1.1_Import_of_Packages'></a>
[1.1_Import_of_Packages](#1.1_Import_of_Packages)




<a id='2_Scrapping-Candidates'></a>
[2_Scrapping-Candidates](#2_Scrapping-Candidates)

 * <a id='Note'></a>
[Note](#Note)

 * <a id='Merging_tables'></a>
[Merging_tables](#Merging_tables)




<a id='3_Scrapping_Results_and_Attendance'></a>
[3_Scrapping_Results_and_Attendance](#3_Scrapping_Results_and_Attendance)

 * <a id='Merging'></a>
[Merging](#Merging)

 * <a id='Saving_Datasets'></a>
[Saving_Datasets](#Saving_Datasets)


####################################################################################

## 1_Introductory
### (Czech only)

  * V rámci tohoto úkolu musíte stáhnout dat z webu (tzv. _web scraping_, velmi základní) a následně data zpracovat a vizualizovat.
  * Cílem bude stáhnout data ze serveru https://www.volby.cz týkající se voleb do zastupitelstva Vámi vybraného (většího) města, uložit tato data v tabulkovém formátu a pak vymyslet vizualizace a zobrazení dat, které umožní orientaci v těchto datech a zvýrazní zajímavé informace a zobrazit přehledně časový vývoj různých veličin.
 
> **Úkoly jsou zadány tak, aby Vám daly prostor pro invenci. Vymyslet _jak přesně_ budete úkol řešit, je důležitou součástí zadání a originalita či nápaditost bude také hodnocena!**

## Výběr zdroje dat

Vyberte si větší město, které má zastupitelstvo druhu 3 (Zastupitelstvo statutárního města) a strojově stáhněte informace o stranách a kandidátkách z následujících let:
 * [2002](https://www.volby.cz/pls/kv2002/kv12?xjazyk=CZ&xid=0), [2006](https://www.volby.cz/pls/kv2006/kv12?xjazyk=CZ&xid=0), [2010](https://www.volby.cz/pls/kv2010/kv12?xjazyk=CZ&xid=0), [2014](https://www.volby.cz/pls/kv2014/kv12?xjazyk=CZ&xid=0) a [2018](https://www.volby.cz/pls/kv2018/kv12?xjazyk=CZ&xid=0).
 

## Pokyny k vypracování


## Poznámky k odevzdání

  * Řiďte se pokyny ze stránky https://courses.fit.cvut.cz/BI-VZD/homeworks/index.html.
  * Odevzdejte nejen Jupyter Notebook, ale i _csv_ soubor(y) se staženými daty.
  * Opravující Vám může umožnit úkol dodělat či opravit a získat tak další body. První verze je ale důležitá a bude-li odbytá, budete za to penalizováni.
  
  
##################################################################################################################################################################################################################

### 1.1_Import_of_Packages

In [1]:
import requests # for robots check
import pandas as pd # for dataframe
import numpy as np # for arrays

In [2]:
print(requests.get("https://www.volby.cz/robots.txt").text)

User-agent: *
Disallow: /pls/

## 2_Scrapping-Candidates

In [3]:
years = [2002, 2006, 2010, 2014, 2018]

df_people = []

for i in years:
    #Looping is done through years, not index + indexed years
    
    url = r"https://www.volby.cz/pls/kv" + str(i) + "/kv21111?xjazyk=CZ&xid=0&xv=11&xdz=3&xnumnuts=4205&xobec=567027&xstrana=0"
    table = pd.read_html(url)
    table[0]= table[0].drop(table[0].index[0:2])      # Two header rows deleted  
    table[0][12] = i                                  # Adding a year of candidature
    
#print(table[0])
    df_people.append(table[0])

#########################################
# Total Candidates:
# 365 + 415 + 394 + 547 + 514 = 2235

In [4]:
df_people[0].head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
2,10,Česká str.sociálně demokrat.,12,Adamcová Svetluša,NaN,42,ČSSD,ČSSD,1 919,2.27,6.0,NaN,2002
3,8,"Koalice KDU-ČSL, SZ",24,Agh Alexandr,NaN,40,SZ,BEZPP,336,1.92,NaN,NaN,2002
4,7,Nezáv.sdruž.sport.města Mostu,3,Augusta Pavel,Ing.,38,SSZ,SSZ,1 099,2.92,3.0,NaN,2002
5,3,Komunistická str.Čech a Moravy,15,Babák Jindřich,NaN,48,KSČM,KSČM,3 749,2.25,1.0,NaN,2002
6,8,"Koalice KDU-ČSL, SZ",10,Babováková Tatiana,JUDr.,48,SZ,BEZPP,484,2.77,NaN,NaN,2002

In [5]:
df_people[0].reset_index(drop = True,inplace=True)


### Note

#### !!!!!!!!!!!!!!!!!!!!
#### In many cases, there is a small warning table besides the output. Anyway, the outputs are correct. 
#### These warnings are somehow connected with indexing
#### !!!!!!!!!!!!!!!!!!!!

In [6]:
# Data from 2002 (df[0]) are in different format, there is a Title column. For better merging I join them to the name as in the other datasets.

for i in range(0, len(df_people[0])):
    if pd.isna(df_people[0][4][i]):
        pass
    else:
        df_people[0][3][i]= df_people[0][3][i] + " " + df_people[0][4][i]

df_people[0].head()

C:\Users\jiri.zelenka\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,10,Česká str.sociálně demokrat.,12,Adamcová Svetluša,NaN,42,ČSSD,ČSSD,1 919,2.27,6.0,NaN,2002
1,8,"Koalice KDU-ČSL, SZ",24,Agh Alexandr,NaN,40,SZ,BEZPP,336,1.92,NaN,NaN,2002
2,7,Nezáv.sdruž.sport.města Mostu,3,Augusta Pavel Ing.,Ing.,38,SSZ,SSZ,1 099,2.92,3.0,NaN,2002
3,3,Komunistická str.Čech a Moravy,15,Babák Jindřich,NaN,48,KSČM,KSČM,3 749,2.25,1.0,NaN,2002
4,8,"Koalice KDU-ČSL, SZ",10,Babováková Tatiana JUDr.,JUDr.,48,SZ,BEZPP,484,2.77,NaN,NaN,2002

In [7]:
# Deleteing original column with Titles

df_people[0] = df_people[0].drop([4], axis = 1)

In [8]:
# All the datasets 2006-2018 have bad percentages

for i in range(5):
    if i == 0:
        pass
    else:
        df_people[i][8] = (df_people[i][8])*(1/100)

In [9]:
# Renaming Columns

for i in range(5):

    df_people[i].reset_index(drop = True,inplace=True)
    df_people[i].columns = [ 0,1,2,3,4,5,6,7,8,9,10, 11]
    display(df_people[i].head())

,0,1,2,3,4,5,6,7,8,9,10,11
0,10,Česká str.sociálně demokrat.,12,Adamcová Svetluša,42,ČSSD,ČSSD,1 919,2.27,6.0,NaN,2002
1,8,"Koalice KDU-ČSL, SZ",24,Agh Alexandr,40,SZ,BEZPP,336,1.92,NaN,NaN,2002
2,7,Nezáv.sdruž.sport.města Mostu,3,Augusta Pavel Ing.,38,SSZ,SSZ,1 099,2.92,3.0,NaN,2002
3,3,Komunistická str.Čech a Moravy,15,Babák Jindřich,48,KSČM,KSČM,3 749,2.25,1.0,NaN,2002
4,8,"Koalice KDU-ČSL, SZ",10,Babováková Tatiana JUDr.,48,SZ,BEZPP,484,2.77,NaN,NaN,2002

,0,1,2,3,4,5,6,7,8,9,10,11
0,7,Sdružení Mostečané Mostu,37,Anderle Miloslav,46,SOS,BEZPP,6 006,2.15,19,-,2006
1,7,Sdružení Mostečané Mostu,12,Antoš Roman,43,NK,BEZPP,6 269,2.25,12,*,2006
2,9,Sdružení pro sport a zdraví,7,Augusta Pavel Ing.,42,SSZ,SSZ,801,2.50,-,-,2006
3,5,Komunistická str.Čech a Moravy,17,Aulický Václav,33,KSČM,BEZPP,2 890,2.23,9,-,2006
4,5,Komunistická str.Čech a Moravy,13,Babák Jindřich,52,KSČM,KSČM,2 949,2.28,5,-,2006

,0,1,2,3,4,5,6,7,8,9,10,11
0,5,Věci veřejné,34,Adámek Vladislav,39,VV,BEZPP,615,2.16,-,-,2010
1,6,Sdružení Mostečané Mostu,32,Anderle Miloslav,50,NK,BEZPP,9 295,2.19,6,-,2010
2,7,Česká str.sociálně demokrat.,10,Andreaová Jaroslava Alexandra JUDr.,58,ČSSD,ČSSD,2 436,2.29,4,-,2010
3,6,Sdružení Mostečané Mostu,13,Antoš Roman,47,S.cz,S.cz,9 542,2.25,13,*,2010
4,1,Komunistická str.Čech a Moravy,11,Aulický Václav,37,KSČM,BEZPP,1 858,2.25,6,-,2010

,0,1,2,3,4,5,6,7,8,9,10,11
0,1,Toryové,33,Adamcová Veronika,48,TOR,BEZPP,193,1.98,-,-,2014
1,14,ANO 2011,23,Agh Alexandr,52,ANO,ANO,1 870,2.28,17,-,2014
2,3,Sdružení Mostečané Mostu,35,Anderle Miloslav,54,NK,BEZPP,2 858,2.17,25,-,2014
3,9,Česká str.sociálně demokrat.,17,Andrea Lukáš DiS.,32,ČSSD,ČSSD,1 070,2.16,14,-,2014
4,9,Česká str.sociálně demokrat.,40,Andreaová Jaroslava Alexandra JUDr.,62,ČSSD,ČSSD,973,1.97,37,-,2014

,0,1,2,3,4,5,6,7,8,9,10,11
0,9,Česká str.sociálně demokrat.,18,Adámek Arnošt,50,ČSSD,ČSSD,492,2.18,-,-,2018
1,5,ANO 2011,8,Agh Alexandr,56,ANO,ANO,2 606,2.33,8,*,2018
2,4,Sdružení Mostečané Mostu,30,Anderle Miloslav,58,NK,BEZPP,2 404,2.16,22,-,2018
3,9,Česká str.sociálně demokrat.,12,Andrea Lukáš Bc. DiS.,36,ČSSD,ČSSD,516,2.29,-,-,2018
4,9,Česká str.sociálně demokrat.,37,Andreaová Jaroslava Alexandra JUDr.,66,ČSSD,ČSSD,486,2.15,-,-,2018

#### Replacing * deleting NaN, changing types to INT everywhere but percentage
* Mandat: "-" -> 0 and * -> 1
* 2006-2018: "-" -> 0
* 2002: NaN -> 0
* Last two columns into INT

In [10]:
# Replacing NaN with 0s

df_people[0].fillna(0, inplace=True)

# Eveyone but 0
for i in range(5):
    if i == 0:
        pass
    else:
        df_people[i]=df_people[i].replace(to_replace ="-", value = "0") 

# Everyone:
for i in range(5):
    df_people[i]=df_people[i].replace(to_replace ="*", value = "1")

In [11]:
display(df_people[i].describe())

for i in range(5):

    df_people[i][0] = df_people[i][0].astype(int)
    df_people[i][2] = df_people[i][2].astype(int)
    df_people[i][4] = df_people[i][4].astype(int)

    df_people[i][9] = df_people[i][9].astype(int)
    df_people[i][10] = df_people[i][10].astype(int)

               8       11
count  514.000000   514.0
mean     2.329728  2018.0
std      0.646423     0.0
min      1.680000  2018.0
25%      2.092500  2018.0
50%      2.190000  2018.0
75%      2.300000  2018.0
max      7.980000  2018.0

### Merging_tables
#### Renaming Columns

In [17]:
frames = [df_people[0], df_people[1], df_people[2], df_people[3], df_people[4]]

candidates = pd.concat(frames)

candidates.reset_index(drop = True,inplace=True)

candidates.columns = ["No_of_Party", "Party", "No_of_candidature", "Name", "Age", "Proposing_party", "Own_party", "Amount_of_votes", "Percentage_of_votes", "Rank_of secundant", "Mandat", "Year_of_candidature"]
candidates = candidates.drop(["No_of_Party"], axis = 1)


display(candidates.head())
display(candidates.tail())

,Party,No_of_candidature,Name,Age,Proposing_party,Own_party,Amount_of_votes,Percentage_of_votes,Rank_of secundant,Mandat,Year_of_candidature
0,Česká str.sociálně demokrat.,12,Adamcová Svetluša,42,ČSSD,ČSSD,1 919,2.27,6,0,2002
1,"Koalice KDU-ČSL, SZ",24,Agh Alexandr,40,SZ,BEZPP,336,1.92,0,0,2002
2,Nezáv.sdruž.sport.města Mostu,3,Augusta Pavel Ing.,38,SSZ,SSZ,1 099,2.92,3,0,2002
3,Komunistická str.Čech a Moravy,15,Babák Jindřich,48,KSČM,KSČM,3 749,2.25,1,0,2002
4,"Koalice KDU-ČSL, SZ",10,Babováková Tatiana JUDr.,48,SZ,BEZPP,484,2.77,0,0,2002

,Party,No_of_candidature,Name,Age,Proposing_party,Own_party,Amount_of_votes,Percentage_of_votes,Rank_of secundant,Mandat,Year_of_candidature
2230,Otevřená radnice Most,40,Zeiler Vilém,45,Hora 2014,BEZPP,343,2.00,0,0,2018
2231,Piráti a Zelení pro Most,6,Zemanová Kateřina MUDr.,48,Zelení,Zelení,1 488,2.45,2,0,2018
2232,Česká str.sociálně demokrat.,39,Zíková Bohumila,41,ČSSD,ČSSD,469,2.08,0,0,2018
2233,ANO 2011,4,Zudová Jana Ing.,35,ANO,ANO,2 687,2.40,4,1,2018
2234,Otevřená radnice Most,17,Zwoliński Josef,50,Hora 2014,BEZPP,390,2.28,0,0,2018

### Titles

In [13]:
candidates.reset_index(drop = True,inplace=True)

candidates["Titul"] = np.nan

MBAs = ["MBA", "BBA"]

##########################
# Vyjádřit se k MBA a BBA a systému
##########################

for i in range(len(candidates)): 
    
    if candidates["Jméno"].iloc[i].split()[-1] in MBAs:
        if candidates["Jméno"].iloc[i].split()[-2][-1]== ".":
            if candidates["Jméno"].iloc[i].split()[-3][-1]== ".":
                candidates["Titul"].iloc[i] = candidates["Jméno"].iloc[i].split()[-3]
            else:
                candidates["Titul"].iloc[i] = candidates["Jméno"].iloc[i].split()[-2]


    else:
        if candidates["Jméno"].iloc[i][-1]== ".":
            if candidates["Jméno"].iloc[i].split()[-2][-1]== ".":
                candidates["Titul"].iloc[i] = candidates["Jméno"].iloc[i].split()[-2]
            else:
                candidates["Titul"].iloc[i] = candidates["Jméno"].iloc[i].split()[-1]

candidates.head(15)

C:\Users\jiri.zelenka\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

,Strana,Číslo_na_kandidátce,Jméno,Věk,Navrhující_strana,Politická_příslušnost,Hlasy_počet,Hlasy_procenta,Pořadí_zvolení_náhradníka,Mandát,Rok_kandidatury,Titul
0,Česká str.sociálně demokrat.,12,Adamcová Svetluša,42,ČSSD,ČSSD,1 919,2.27,6,0,2002,NaN
1,"Koalice KDU-ČSL, SZ",24,Agh Alexandr,40,SZ,BEZPP,336,1.92,0,0,2002,NaN
2,Nezáv.sdruž.sport.města Mostu,3,Augusta Pavel Ing.,38,SSZ,SSZ,1 099,2.92,3,0,2002,Ing.
3,Komunistická str.Čech a Moravy,15,Babák Jindřich,48,KSČM,KSČM,3 749,2.25,1,0,2002,NaN
4,"Koalice KDU-ČSL, SZ",10,Babováková Tatiana JUDr.,48,SZ,BEZPP,484,2.77,0,0,2002,JUDr.
5,Sdružení nezávislých,29,Bachura Milan,28,SNK ED,BEZPP,1 226,1.92,24,0,2002,NaN
6,Občanská demokratická strana,16,Bajer Miloslav Mgr.,58,ODS,ODS,3 373,2.39,7,0,2002,Mgr.
7,Komunistická str.Čech a Moravy,19,Balín Roman,21,KSČM,BEZPP,3 695,2.22,5,0,2002,NaN
8,Komunistická str.Čech a Moravy,1,Balín Vlastimil RSDr.,52,KSČM,KSČM,4 064,2.44,1,1,2002,RSDr.
9,Česká str.sociálně demokrat.,26,Balogová Lenka,37,ČSSD,ČSSD,1 852,2.19,19,0,2002,NaN
10,"Koalice KDU-ČSL, SZ",38,Bartes Petr,28,KDU-ČSL,BEZPP,307,1.76,0,0,2002,NaN
11,Občanská demokratická strana,41,Bártl Čestmír,67,ODS,ODS,2 706,1.91,30,0,2002,NaN
12,Občanská demokratická strana,1,Bártl Vladimír Ing.,41,ODS,ODS,3 987,2.82,1,1,2002,Ing.
13,Komunistická str.Čech a Moravy,20,Bartošová Jana,58,KSČM,KSČM,3 754,2.25,6,0,2002,NaN
14,Nezáv.sdruž.sport.města Mostu,18,Bejček Josef,46,SSZ,BEZPP,704,1.87,16,0,2002,NaN

### Rearanging Columns

In [14]:
candidates = candidates[["Jméno", "Titul", "Věk", "Strana", "Navrhující_strana", "Politická_příslušnost", "Číslo_na_kandidátce", "Hlasy_počet", "Hlasy_procenta", "Pořadí_zvolení_náhradníka", "Mandát", "Rok_kandidatury"]]
        
candidates.head(15)

,Jméno,Titul,Věk,Strana,Navrhující_strana,Politická_příslušnost,Číslo_na_kandidátce,Hlasy_počet,Hlasy_procenta,Pořadí_zvolení_náhradníka,Mandát,Rok_kandidatury
0,Adamcová Svetluša,NaN,42,Česká str.sociálně demokrat.,ČSSD,ČSSD,12,1 919,2.27,6,0,2002
1,Agh Alexandr,NaN,40,"Koalice KDU-ČSL, SZ",SZ,BEZPP,24,336,1.92,0,0,2002
2,Augusta Pavel Ing.,Ing.,38,Nezáv.sdruž.sport.města Mostu,SSZ,SSZ,3,1 099,2.92,3,0,2002
3,Babák Jindřich,NaN,48,Komunistická str.Čech a Moravy,KSČM,KSČM,15,3 749,2.25,1,0,2002
4,Babováková Tatiana JUDr.,JUDr.,48,"Koalice KDU-ČSL, SZ",SZ,BEZPP,10,484,2.77,0,0,2002
5,Bachura Milan,NaN,28,Sdružení nezávislých,SNK ED,BEZPP,29,1 226,1.92,24,0,2002
6,Bajer Miloslav Mgr.,Mgr.,58,Občanská demokratická strana,ODS,ODS,16,3 373,2.39,7,0,2002
7,Balín Roman,NaN,21,Komunistická str.Čech a Moravy,KSČM,BEZPP,19,3 695,2.22,5,0,2002
8,Balín Vlastimil RSDr.,RSDr.,52,Komunistická str.Čech a Moravy,KSČM,KSČM,1,4 064,2.44,1,1,2002
9,Balogová Lenka,NaN,37,Česká str.sociálně demokrat.,ČSSD,ČSSD,26,1 852,2.19,19,0,2002
10,Bartes Petr,NaN,28,"Koalice KDU-ČSL, SZ",KDU-ČSL,BEZPP,38,307,1.76,0,0,2002
11,Bártl Čestmír,NaN,67,Občanská demokratická strana,ODS,ODS,41,2 706,1.91,30,0,2002
12,Bártl Vladimír Ing.,Ing.,41,Občanská demokratická strana,ODS,ODS,1,3 987,2.82,1,1,2002
13,Bartošová Jana,NaN,58,Komunistická str.Čech a Moravy,KSČM,KSČM,20,3 754,2.25,6,0,2002
14,Bejček Josef,NaN,46,Nezáv.sdruž.sport.města Mostu,SSZ,BEZPP,18,704,1.87,16,0,2002

### Úprava posledního sloupce - počet hlasů

In [ ]:
for i in range(len(ucastnici)):
    if len(ucastnici['Hlasy_počet'][i]) == 2:
        ucastnici['Hlasy_počet'][i] = ucastnici['Hlasy_počet'][i][-2:]
    elif len(ucastnici['Hlasy_počet'][i]) == 3:
        ucastnici['Hlasy_počet'][i] = ucastnici['Hlasy_počet'][i][-3:]
    elif len(ucastnici['Hlasy_počet'][i]) == 5:
        ucastnici['Hlasy_počet'][i] = ucastnici['Hlasy_počet'][i][0] + ucastnici['Hlasy_počet'][i][-3:]
    elif len(ucastnici['Hlasy_počet'][i]) == 6:
        ucastnici['Hlasy_počet'][i] = ucastnici['Hlasy_počet'][i][0:2] + ucastnici['Hlasy_počet'][i][-3:] 
    else:
        pass

In [ ]:
# Poslední úprava typu na Int + Kontrola Typů

ucastnici["Hlasy_počet"] = ucastnici["Hlasy_počet"].astype(int)
display(ucastnici.dtypes)

#### Závěrečná kontrola datasetu

In [ ]:
ucastnici.describe()

## 3_Scrapping_Results_and_Attendance

In [ ]:
roky = [2002, 2006, 2010, 2014, 2018]

df_ucast = []
df_vysledky = []

for i in roky:
    url = r"https://www.volby.cz/pls/kv" + str(i) + "/kv1111?xjazyk=CZ&xid=1&xdz=3&xnumnuts=4205&xobec=567027"
    table = pd.read_html(url)
    table[0]= table[0].drop(table[0].index[0:2])    # Odmazány první dva řádky záhlaví
    table[1]= table[1].drop(table[1].index[0:2])    # Odmazány první dva řádky záhlaví
   
    table[1][9] = i 
    
    df_ucast.append(table[0])
    df_vysledky.append(table[1])

In [ ]:
# Kontrola nahraných dat

for i in range(5):

    display(df_ucast[i].head())
    display(df_vysledky[i].head(20))

In [ ]:
# Resetování indexů

for i in range(5):
    df_ucast[i].reset_index(drop = True,inplace=True)
    df_vysledky[i].reset_index(drop = True,inplace=True)

#### a) Pouze počet oprávněných voličů a výsledná účast

In [ ]:
# Ponechání pouze dvou sloupců

for i in range(5):
    df_ucast[i] = df_ucast[i][[5,7]]
    display(df_ucast[i])

df_ucast[i].reset_index(drop = True,inplace=True)

In [ ]:
# Změna typu sloupců, Přenásobení na procenta

for i in range(5):
    df_ucast[i][7]=pd.to_numeric(df_ucast[i][7]) 
    
    if i ==0:
        pass
    else:
        df_ucast[i][7] = df_ucast[i][7]*(1/100)
        
    display(df_ucast[i])

#### Merging

In [ ]:
# Merging, reindexing, přejmenování sloupců, přidání roku

frames2 = [df_ucast[0], df_ucast[1], df_ucast[2], df_ucast[3], df_ucast[4]]

ucast = pd.concat(frames2)

ucast.reset_index(drop = True,inplace=True)

ucast.columns = ["Opravneni_volici", "Ucast_procent"]

ucast["Rok"] = roky

In [ ]:
ucast

In [ ]:
for i in range(len(ucast)):
    if len(ucast['Opravneni_volici'][i]) == 2:
        ucast['Opravneni_volici'][i] = ucast['Opravneni_volici'][i][-2:]
    elif len(ucast['Opravneni_volici'][i]) == 3:
        ucast['Opravneni_volici'][i] = ucast['Opravneni_volici'][i][-3:]
    elif len(ucast['Opravneni_volici'][i]) == 5:
        ucast['Opravneni_volici'][i] = ucast['Opravneni_volici'][i][0] + ucast['Opravneni_volici'][i][-3:]
    elif len(ucast['Opravneni_volici'][i]) == 6:
        ucast['Opravneni_volici'][i] = ucast['Opravneni_volici'][i][0:2] + ucast['Opravneni_volici'][i][-3:] 
    else:
        pass

In [ ]:
# Poslední úprava typu na Int + Kontrola Typů

ucast["Opravneni_volici"] = ucast["Opravneni_volici"].astype(int)
display(ucast.dtypes)

ucast.describe()

#### b) Výsledky voleb - doupravení

In [ ]:
for i in range(2):
       display(df_vysledky[i])

#### Úprava typů a Procenta (krom 1. setu)

In [ ]:
for i in range(2):
    display(df_vysledky[i].dtypes)

In [ ]:
for i in range(5):
        if i == 0:
            pass
        else:
            df_vysledky[i][0] = df_vysledky[i][0].astype(int)
            df_vysledky[i][3] = df_vysledky[i][3].astype(int)
            df_vysledky[i][4] = df_vysledky[i][4].astype(int)
            df_vysledky[i][6] = df_vysledky[i][6].astype(int)
            df_vysledky[i][7] = df_vysledky[i][7].astype(int)

df_vysledky[0][0] = df_vysledky[0][0].astype(int)
df_vysledky[0][4] = df_vysledky[0][4].astype(int)
df_vysledky[0][7] = df_vysledky[0][7].astype(int)

df_vysledky[0][3] = df_vysledky[0][3].astype(float)
df_vysledky[0][6] = df_vysledky[0][6].astype(float)

In [ ]:
for i in range(5):
    if i == 0:
        pass
    else:
        df_vysledky[i][3] = (df_vysledky[i][3])*(1/100)
        df_vysledky[i][6] = (df_vysledky[i][6])*(1/100)

#### Replacing znaků - není potřeba, drop posledního sloupce

#### Merging + Pojmenování a zvolení sloupců

In [ ]:
frames3 = [df_vysledky[0], df_vysledky[1], df_vysledky[2], df_vysledky[3], df_vysledky[4]]

vysledky = pd.concat(frames3)

vysledky.reset_index(drop = True,inplace=True)

vysledky.columns = ["Číslo_strany", "Strana", "Počet_hlasů", "Procento_hlasů", "Počet_kandidátů", "Přepočtený_počet_hlasů", "Přepočtené_procento_hlasů", "Počet_mandátů", "Mandáty", "Rok"]
vysledky = vysledky.drop(["Číslo_strany","Přepočtený_počet_hlasů", "Přepočtené_procento_hlasů", "Mandáty"], axis = 1)


display(vysledky.head())
display(vysledky.tail())

#### Dodělání sloupců s tisíci na INT

In [ ]:
vysledky.reset_index(drop = True,inplace=True)

In [ ]:
for i in range(len(vysledky)):
    if len(vysledky['Počet_hlasů'][i]) == 2:
        vysledky['Počet_hlasů'][i] = vysledky['Počet_hlasů'][i][-2:]
    elif len(vysledky['Počet_hlasů'][i]) == 3:
        vysledky['Počet_hlasů'][i] = vysledky['Počet_hlasů'][i][-3:]
    elif len(vysledky['Počet_hlasů'][i]) == 5:
        vysledky['Počet_hlasů'][i] = vysledky['Počet_hlasů'][i][0] + vysledky['Počet_hlasů'][i][-3:]
    elif len(vysledky['Počet_hlasů'][i]) == 6:
        vysledky['Počet_hlasů'][i] = vysledky['Počet_hlasů'][i][0:2] + vysledky['Počet_hlasů'][i][-3:] 
    elif len(vysledky['Počet_hlasů'][i]) == 7:
        vysledky['Počet_hlasů'][i] = vysledky['Počet_hlasů'][i][0:3] + vysledky['Počet_hlasů'][i][-3:]      # Přidáno toto prodloužení na 6 místné čísla
    else:
        pass

    
vysledky["Počet_hlasů"] = vysledky["Počet_hlasů"].astype(int)

In [ ]:
display(vysledky.dtypes)

display(vysledky.head())

vysledky.describe()

### Saving_Datasets
##### Účastníci
##### Účast
##### Výsledky

In [ ]:
ucastnici.to_excel(r'kandidati.xlsx')
ucast.to_excel(r'ucast.xlsx')
vysledky.to_excel(r'vysledky.xlsx')

In [ ]:
ucastnici.to_csv(r'kandidati.csv')
ucast.to_csv(r'ucast.csv')
vysledky.to_csv(r'vysledky.csv')